-- 회원 정보 테이블
CREATE TABLE distep.TH_MEMBER (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    PSN_NM VARCHAR2(100),
    CP_NO VARCHAR2(20) -- 전화번호 컬럼도 사용되고 있음
);

-- SMS 전송 기록 테이블
CREATE TABLE distep.SMS (
    CMP_MSG_ID VARCHAR2(20) PRIMARY KEY,
    CMP_USR_ID VARCHAR2(20),
    ODR_FG CHAR(1),
    SMS_GB CHAR(1),
    USED_CD CHAR(2),
    MSG_GB CHAR(1),
    WRT_DTTM VARCHAR2(14),
    SND_DTTM VARCHAR2(14),
    SND_PHN_ID VARCHAR2(20),
    RCV_PHN_ID VARCHAR2(20),
    CALLBACK VARCHAR2(20),
    SND_MSG VARCHAR2(2000),
    SMS_ST CHAR(1),
    USER_ID VARCHAR2(50),
    FOREIGN KEY (USER_ID) REFERENCES distep.TH_MEMBER(USER_ID)
);

CREATE SEQUENCE TAB_ETC_DATA_APP_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 첨부파일 일련번호용 시퀀스
CREATE SEQUENCE TAB_ATTACH_FILE_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TAB_ATTACH_FILE (
    ATTACH_FILE_SN NUMBER PRIMARY KEY,
    BLTNBRD_SN NUMBER,
    FILE_CD VARCHAR2(20),
    SN NUMBER,
    ATTACH_FILE_NM VARCHAR2(255),
    ATTACH_FILE_SAVE_NM VARCHAR2(255),
    ATTACH_FILE_SZ NUMBER,
    REGISTER_ID VARCHAR2(50),
    REGIST_DT DATE,
    USE_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE TB_SYSTEM_CD (
    CD VARCHAR2(20) PRIMARY KEY,
    CD_NM VARCHAR2(255),
    GRP_CD VARCHAR2(20),
    STD_CD_YN CHAR(1),
    OPTION1 VARCHAR2(20),
    OPTION2 VARCHAR2(20),
    UPPER_CD VARCHAR2(20)
);

CREATE TABLE distep.TB_CLASS_CD (
    CLASS_CD VARCHAR2(20) PRIMARY KEY,
    CLASS_NM VARCHAR2(255),
    CLASS_GRP VARCHAR2(20),
    KIND_CD VARCHAR2(20),
    UPPER_CLASS_CD VARCHAR2(20),
    VALIDITY_FROM_DT DATE,
    VALIDITY_TO_DT DATE,
    CLASS_SEQ NUMBER
);

CREATE TABLE AS_APPLDATA_ITEM (
    DIV VARCHAR2(20),
    SN NUMBER,
    ITEM_NM VARCHAR2(255),
    -- 추가 컬럼 필요시 확장 가능
    PRIMARY KEY (DIV, SN)
);

CREATE TABLE AS_USER_APPLDATA_CND (
    SEQ NUMBER PRIMARY KEY,
    TYPE VARCHAR2(20),
    USER_ID VARCHAR2(50),
    RSCH_EXEC_SUJ_CD VARCHAR2(20),
    RSCH_EXEC_SUJ_NM VARCHAR2(255),
    REGN_SLCT_CD VARCHAR2(20),
    REGN_SLCT_NM VARCHAR2(255),
    RSCH_AREA_CD VARCHAR2(20),
    NAT_STRT_TECH_CD VARCHAR2(20),
    T6TECH_CD VARCHAR2(20),
    SEARCH_KWRD VARCHAR2(4000),
    CHK_STANYRS VARCHAR2(4000),
    CHK_PJT_ITEM VARCHAR2(4000),
    CHK_PAPER_ITEM VARCHAR2(4000),
    CHK_IPR_ITEM VARCHAR2(4000),
    ALL_APPLDATA_CND_NM VARCHAR2(4000),
    REGIST_DT DATE,
    KEYWORD_ITEM1 VARCHAR2(4000),
    KEYWORD_ITEM2 VARCHAR2(4000),
    KEYWORDCND_ITEM VARCHAR2(4000),
    PURPOSE VARCHAR2(4000),
    REQUEST_CN VARCHAR2(4000),
    RELATED_NOTICE_FILE_ATTCH_FILE VARCHAR2(4000),
    DATA_REQUEST_FORM_ATTCH_FILE VARCHAR2(4000),
    SIGN_STAT_CD VARCHAR2(20),
    BLNG_ORG_CD VARCHAR2(20),
    CHK_PJT_ITEM_NM VARCHAR2(4000),
    CHK_PAPER_ITEM_NM VARCHAR2(4000),
    CHK_IPR_ITEM_NM VARCHAR2(4000),
    CHK_APPL_DATA_CD VARCHAR2(20),
    BLNG_ORG_NM VARCHAR2(255),
    TITLE VARCHAR2(4000),
    VIEWCNT NUMBER DEFAULT 0,
    OPEN_YN CHAR(1),
    CHK_CHART CHAR(1)
);

CREATE SEQUENCE USER_APPLDATA_CND_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

commit
;


-- 게시판 테이블
CREATE TABLE DISTEP.KAB_BOARD (
    BBS_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(400),
    USER_ID VARCHAR2(50),
    USER_NAME VARCHAR2(100),
    CONTENTS CLOB,
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE,
    DELETE_AT CHAR(1) DEFAULT 'N',
    DELETE_DATE DATE,
    HITS NUMBER DEFAULT 0
);

-- 댓글 테이블
CREATE TABLE DISTEP.KAB_COMMENT (
    COMMENT_ID NUMBER PRIMARY KEY,
    BBS_ID NUMBER,
    USER_ID VARCHAR2(50),
    USER_NAME VARCHAR2(100),
    CONTENTS VARCHAR2(4000),
    PARENT_COMMENT_ID NUMBER DEFAULT 0,
    CREATE_DATE DATE DEFAULT SYSDATE,
    UPDATE_DATE DATE,
    DELETE_AT CHAR(1) DEFAULT 'N',
    DELETE_DATE DATE,
    FOREIGN KEY (BBS_ID) REFERENCES DISTEP.KAB_BOARD(BBS_ID)
);

-- 좋아요 테이블
CREATE TABLE DISTEP.KAB_LIKE (
    LIKE_ID NUMBER PRIMARY KEY,
    BBS_ID NUMBER,
    USER_ID VARCHAR2(50),
    CREATE_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (BBS_ID) REFERENCES DISTEP.KAB_BOARD(BBS_ID)
);

-- 첨부파일 테이블
CREATE TABLE DISTEP.KAB_ATTACH_FILE (
    ATTACH_FILE_SN NUMBER PRIMARY KEY,
    BBS_ID NUMBER,
    SN NUMBER,
    ATTACH_FILE_NM VARCHAR2(400),
    ATTACH_FILE_SAVE_NM VARCHAR2(400),
    ATTACH_FILE_SZ NUMBER,
    USER_ID VARCHAR2(50),
    CREATE_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (BBS_ID) REFERENCES DISTEP.KAB_BOARD(BBS_ID)
);


-- 게시판 ID 생성용 시퀀스
CREATE SEQUENCE DISTEP.KAB_BOARD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 댓글 ID 생성용 시퀀스
CREATE SEQUENCE DISTEP.KAB_COMMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 좋아요 ID 생성용 시퀀스
CREATE SEQUENCE DISTEP.KAB_LIKE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 첨부파일 SN 생성용 시퀀스
CREATE SEQUENCE DISTEP.KAB_ATTACH_FILE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

commit;













